#!/usr/bin/env python

if (__name__ == '__main__'):
    from zensols.cli import ConfigurationImporterCliHarness
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.propbankdb.ApplicationFactory',
        #config_path='test-resources/propbankdb.conf',
        proto_args='proto',
        proto_factory_kwargs={'reload_pattern': r'^zensols.propbankdb'},
    )
    harness.configure_logging()
    harness.run()
